variable "VPC_ID" {}
variable "PUB_PORT" {}
variable "PRI_PORT" {}
variable "PRIVATE_SUBNET_CIDR" {}
variable "PUBLIC_SUBNET_ID" {}
variable "PRIVATE_SUBNET_ID" {}
variable "PROJECT" {}
variable "ENV" {}
variable "PUBLIC_HOSTED_ZONE_ID" {}
